### ISSUE TITLE
Crash on Win32/Debug

### ISSUE THREAD

**Issue by tueddy** [andrea-magni/ScannerMApp#2]
Hi,

i get a crash when i start the app with win32/debug and close it without doing anything.
Call stack:
![grafik](https://user-images.githubusercontent.com/11274319/28579975-745b98fc-715e-11e7-86c5-50add79e027a.png)

**Comment by tueddy** [comment]
OK, Access violation occours only with TFrameStand from GetIt, using the GitHub component works fine.
Is GetIt component out of date?
Best regards
Dirk

**Comment by andrea-magni** [comment]
The version on GetIt is a couple of commit behind. I will ask for an update soon (I'd like to add a new feature at least before asking for an update).

Thanks
